export const EVENTS = [
  {
    id: 1,
    name: "SCORE San Felipe 250",
    type: "Carrera Off-Road",
    startDate: "2025-04-12",
    endDate: "2025-04-13",
    location: "San Felipe, Baja California",
    coordenadas: {
      latitud: 30.9752,
      longitud: -114.8394,
    },
    description:
      "Carrera de off-road de 250 millas a través del desierto de San Felipe.",
    image: "sanfelipe250.jpg",
    website: "https://score-international.com/raceinfo/san-felipe-250/",
    categories: ["Trophy Truck", "Class 1", "UTV", "Moto"],
  },
  {
    id: 2,
   name: "Baja 1000 - Tramo San Felipe",
    type: "Carrera Off-Road",
    startDate: "2025-11-15",
    endDate: "2025-11-19",
    location: "San Felipe - La Paz, Baja California",
    coordinates: {
      latitude: 30.9752,
      longitude: -114.8394,
    },
    description:
      "Sección del legendario Baja 1000 que pasa por San Felipe en su ruta a La Paz.",
    image: "baja1000.jpg",
    website: "https://score-international.com/raceinfo/baja-1000/",
    categories: ["Trophy Truck", "Class 1", "UTV", "Moto", "Quad"],
  },
  {
    id: 3,
   name: "Festival del Camarón",
    type: "Festival Gastronómico",
    startDate: "2025-03-28",
    endDate: "2025-03-30",
    location: "Malecón de San Felipe",
    coordinates: {
      latitude: 30.993,
      longitude: -114.8291,
    },
    description:
      "Festival anual que celebra la gastronomía local, con énfasis en el camarón de San Felipe.",
    image: "festivalcamaron.jpg",
    website: "https://www.sanfelipe.com.mx/festival-del-camaron",
    categories: ["Gastronomía", "Cultural"],
  },
  {
    id: 4,
   name: "Torneo de Pesca Deportiva",
    type: "Evento Deportivo",
    startDate: "2025-05-17",
    endDate: "2025-05-18",
    location: "Marina de San Felipe",
    coordinates: {
      latitude: 30.9965,
      longitude: -114.8299,
    },
    description:
      "Competencia de pesca deportiva con categorías para diferentes especies marinas.",
    image: "torneopesca.jpg",
    website: "https://www.sanfelipedeportes.mx/pesca",
    categories: ["Pesca", "Deportivo"],
  },
  {
    id: 5,
   name: "San Felipe Blues & Arts Festival",
    type: "Festival Musical",
    startDate: "2025-02-14",
    endDate: "2025-02-16",
    location: "Playa de San Felipe",
    coordinates: {
      latitude: 30.991,
      longitude: -114.828,
    },
    description:
      "Festival de música blues y artes visuales en la playa de San Felipe.",
    image: "bluesfestival.jpg",
    website: "https://sanfelipebluesfest.com",
    categories: ["Música", "Arte", "Cultural"],
  },
  {
    id: 6,
   name: "Carrera Ciclista Valle de los Gigantes",
    type: "Ciclismo",
    startDate: "2025-09-20",
    endDate: "2025-09-20",
    location: "Valle de los Gigantes, San Felipe",
    coordinates: {
      latitude: 31.033,
      longitude: -114.8485,
    },
    description:
      "Carrera de ciclismo de montaña a través del Valle de los Gigantes y sus cactos monumentales.",
    image: "ciclistagigantes.jpg",
    website: "https://www.cyclingbaja.com/vallegigantes",
    categories: ["Ciclismo", "Deportivo"],
  },
  {
    id: 7,
   name: "Expo Turística San Felipe",
    type: "Feria",
    startDate: "2025-10-11",
    endDate: "2025-10-12",
    location: "Centro de Convenciones San Felipe",
    coordinates: {
      latitude: 30.98,
      longitude: -114.835,
    },
    description:
      "Feria que reúne a prestadores de servicios turísticos y artesanos locales.",
    image: "expoturistica.jpg",
    website: "https://www.sanfelipe.gob.mx/expoturistica",
    categories: ["Turismo", "Comercial"],
  },
  {
    id: 8,
   name: "Campeonato de Volleyball Playero",
    type: "Evento Deportivo",
    startDate: "2025-06-05",
    endDate: "2025-06-07",
    location: "Playa El Dorado, San Felipe",
    coordinates: {
      latitude: 30.9947,
      longitude: -114.8275,
    },
    description:
      "Torneo de volleyball playero con equipos nacionales e internacionales.",
    image: "volleyball.jpg",
    website: "https://www.voleiplayero.mx/sanfelipe",
    categories: ["Volleyball", "Deportivo"],
  },
];
